import {
    Airplane,
    ArrowsLeftRight,
    Barbell,
    Bed,
    BeerStein,
    Bicycle,
    Boat,
    Bus,
    Camera,
    Car,
    Coffee,
    DotsThreeCircle,
    FilmSlate,
    FirstAid,
    ForkKnife,
    GasPump,
    Gift,
    Hamburger,
    Heart,
    IceCream,
    MapPinArea,
    Martini,
    Money,
    Mountains,
    Park,
    Phone,
    Pill,
    ShoppingCart,
    SquaresFour,
    Suitcase,
    SwimmingPool,
    Taxi,
    Tent,
    Ticket,
    Tote,
    Train,
    TShirt,
    UmbrellaSimple,
    WifiHigh,
    Wine,
    type Icon,
} from '@phosphor-icons/react'

import {
    DEFAULT_CATEGORY_ICON,
    isCategoryIconName,
    type CategoryIconName,
} from '@/lib/category-icons'

/** Every curated category icon name → its Phosphor component (lib/category-icons.ts lists them). */
const CATEGORY_ICON_COMPONENTS: Record<CategoryIconName, Icon> = {
    Airplane,
    ArrowsLeftRight,
    Barbell,
    Bed,
    BeerStein,
    Bicycle,
    Boat,
    Bus,
    Camera,
    Car,
    Coffee,
    DotsThreeCircle,
    FilmSlate,
    FirstAid,
    ForkKnife,
    GasPump,
    Gift,
    Hamburger,
    Heart,
    IceCream,
    MapPinArea,
    Martini,
    Money,
    Mountains,
    Park,
    Phone,
    Pill,
    ShoppingCart,
    SquaresFour,
    Suitcase,
    SwimmingPool,
    Taxi,
    Tent,
    Ticket,
    Tote,
    Train,
    TShirt,
    UmbrellaSimple,
    WifiHigh,
    Wine,
}

/** A category icon by its stored name (unknown names → the default). */
export function CategoryGlyph({ icon, size }: { icon: string | null | undefined; size: number }) {
    const Glyph = CATEGORY_ICON_COMPONENTS[isCategoryIconName(icon) ? icon : DEFAULT_CATEGORY_ICON]
    return <Glyph size={size} />
}
